import Head from "next/head";
import dynamic from "next/dynamic";

const Menu = dynamic(() => import("@/components/Templates/Menu"));
const MainContent = dynamic(() => import("@/components/Templates/MainContent"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Meta Weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/svg/nodata.svg" />
      </Head>
      <main className="h-screen bg-purple-dark text-white">
        <div className="flex flex-col lg:flex-row">
          <div className="lg:w-1/4">
            <Menu />
          </div>
          <div className="lg:w-3/4">
            <MainContent />
          </div>
        </div>
      </main>
    </>
  );
}
