import Head from "next/head";
import dynamic from "next/dynamic";
import { useState } from "react";
import {
  useTodayWeather,
  useDailyWeather,
} from "@/data/weather-fetch-resources";
import { useCity } from "@/context/city/city.context";
import { useUnit } from "@/context/unit/unit.context";

const Menu = dynamic(() => import("@/components/Templates/Menu"));
const MainContent = dynamic(() => import("@/components/Templates/MainContent"));

function Home() {
  const { code } = useCity();
  const { unit } = useUnit();

  const { currentWeather, currentWeatherIsLoading, currentWeatherError } =
    useTodayWeather({
      cityId: code,
      key: process.env.NEXT_PUBLIC_API_KEY || "",
      units: unit,
    });

  const { dailyWeather, dailyWeatherIsLoading, dailyWeatherError } =
    useDailyWeather({
      cityId: code,
      key: process.env.NEXT_PUBLIC_API_KEY || "",
      units: unit,
    });

  return (
    <>
      <Head>
        <title>Meta Weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/svg/nodata.svg" />
      </Head>

      <main className="bg-purple-dark text-white">
        <div className="flex flex-col lg:flex-row">
          <div className="lg:w-1/4">
            <Menu loading={currentWeatherIsLoading} data={currentWeather} />
          </div>
          <div className="lg:w-3/4">
            <MainContent
              todayLoading={currentWeatherIsLoading}
              todayData={currentWeather}
              dailyLoading={dailyWeatherIsLoading}
              dailyData={dailyWeather}
            />
          </div>
        </div>
      </main>
    </>
  );
}

export default Home;
